name: rainbow_challenge
description: Rainbow challenge

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^7.3.0
  meta: ^1.3.0
  equatable: ^2.0.3
  uuid: ^3.0.4
  http: ^0.13.3
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  connectivity_plus: ^2.0.2
  linter: ^1.12.0

  # A Flutter widget for rendering HTML and CSS as Flutter widgets.
  flutter_html: ^2.1.2
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap-Regular.ttf
        - asset: assets/fonts/Asap-Italic.ttf
          style: italic
        - asset: assets/fonts/Asap-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Asap-SemiBoldItalic.ttf
          style: italic
          weight: 600
    - family: Alumni Sans
      fonts:
        - asset: assets/fonts/AlumniSans-Regular.ttf
        - asset: assets/fonts/AlumniSans-Italic.ttf
          style: italic
        - asset: assets/fonts/AlumniSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AlumniSans-SemiBoldItalic.ttf
          style: italic
          weight: 600